language: python

services:
  - docker

before_install:
  - docker build -t simonsfoundation/caiman .


script:
  - docker run -i -d -p 127.0.0.1:80:4567 simonsfoundation/caiman /bin/sh -c "nosetests"
  - docker ps -a
  - docker run simonsfoundation/caiman /bin/sh -c "nosetests"


# whitelist
branches:
  only:
    # - testing
    # - CNMF2
    # - anaconda
    # - docker
    - master
    # - agiovann-master
    # - dev
